stages:
  - build
  - test
  - deploy

image: openjdk:12-alpine

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs

smoke test:
  stage: test
  script:
    - apk --no-cache add curl
    - java -jar ./build/libs/cars-api.jar &
    - sleep 30
    - curl http://localhost:5000/statistics/age | grep "3"

aws deploy :
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - aws s3 cp ./build/libs/cars-api.jar s3://$S3_INSTANCE/cars-api.jar || { echo "Upload failed"; exit 1; }